<?php

namespace AppBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    public function count()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT (p.id) FROM AppBundle:Client p '
            )
            ->getSingleScalarResult();
    }

}
