app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

dashboard:
    path:      /
    defaults:  { _controller: AppBundle:Admin:index }

addclient:
    path:      /clients/new
    defaults:  { _controller: AppBundle:Client:new }

editclient:
    path:      /clients/{id}/edit
    defaults:  { _controller: AppBundle:Client:edit }
    requirements:
            id: \d+
deleteclient:
    path:      /clients/{id}/delete
    defaults:  { _controller: AppBundle:Client:delete }
    requirements:
            id: \d+
    options:
            expose: true

listclient:
    path:      /clients
    defaults:  { _controller: AppBundle:Client:showAll }


addfournisseur:
    path:      /fournisseurs/new
    defaults:  { _controller: AppBundle:Fournisseur:new }

editfournisseur:
    path:      /fournisseurs/{id}/edit
    defaults:  { _controller: AppBundle:Fournisseur:edit }
    requirements:
            id: \d+
deletefournisseur:
    path:      /fournisseurs/{id}/delete
    defaults:  { _controller: AppBundle:Fournisseur:delete }
    requirements:
            id: \d+
    options:
            expose: true

listfournisseur:
    path:      /fournisseurs
    defaults:  { _controller: AppBundle:Fournisseur:showAll }






