app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

dashboard:
    path:      /
    defaults:  { _controller: AppBundle:Admin:index }

#--------------------- Clients -------------------#
addclient:
    path:      /clients/new
    defaults:  { _controller: AppBundle:Client:new }

editclient:
    path:      /clients/{id}/edit
    defaults:  { _controller: AppBundle:Client:edit }
    requirements:
            id: \d+
deleteclient:
    path:      /clients/{id}/delete
    defaults:  { _controller: AppBundle:Client:delete }
    requirements:
            id: \d+
    options:
            expose: true

listclient:
    path:      /clients
    defaults:  { _controller: AppBundle:Client:showAll }

#--------------------- Entrepots -------------------#
addentrepot:
    path:      /entrepots/new
    defaults:  { _controller: AppBundle:Entrepot:new }

editentrepot:
    path:      /entrepots/{id}/edit
    defaults:  { _controller: AppBundle:Entrepot:edit }
    requirements:
            id: \d+
deleteentrepot:
    path:      /entrepots/{id}/delete
    defaults:  { _controller: AppBundle:Entrepot:delete }
    requirements:
            id: \d+
    options:
            expose: true

listentrepots:
    path:      /entrepots
    defaults:  { _controller: AppBundle:Entrepot:showAll }

#--------------------- Devises -------------------#
adddevise:
    path:      /devises/new
    defaults:  { _controller: AppBundle:Devise:new }

editdevise:
    path:      /devises/{id}/edit
    defaults:  { _controller: AppBundle:Devise:edit }
    requirements:
            id: \d+
deletedevise:
    path:      /devises/{id}/delete
    defaults:  { _controller: AppBundle:Devise:delete }
    requirements:
            id: \d+
    options:
            expose: true

listdevises:
    path:      /devises
    defaults:  { _controller: AppBundle:Devise:showAll }

#--------------------- Taxes -------------------#
addtaxe:
    path:      /taxes/new
    defaults:  { _controller: AppBundle:Taxe:new }

editetaxe:
    path:      /taxes/{id}/edit
    defaults:  { _controller: AppBundle:Taxe:edit }
    requirements:
            id: \d+
deletetaxe:
    path:      /taxes/{id}/delete
    defaults:  { _controller: AppBundle:Taxe:delete }
    requirements:
            id: \d+
    options:
            expose: true

listtaxes:
    path:      /taxes
    defaults:  { _controller: AppBundle:Taxe:showAll }


#--------------------- Fournisseurs -------------------#
addfournisseur:
    path:      /fournisseurs/add
    defaults:  { _controller: AppBundle:Fournisseur:new }

editfournisseur:
    path:      /fournisseurs/{id}/edit
    defaults:  { _controller: AppBundle:Fournisseur:edit }
    requirements:
            id: \d+
deletefournisseur:
    path:      /fournisseurs/{id}/delete
    defaults:  { _controller: AppBundle:Fournisseur:delete }
    requirements:
            id: \d+
    options:
            expose: true

listfournisseur:
    path:      /fournisseurs
    defaults:  { _controller: AppBundle:Fournisseur:showAll }


#--------------------- Categories -------------------#
listcategories:
    path:      /categories
    defaults:  { _controller: AppBundle:Category:showAll }

editcategorie:
    path:      /categories/{id}/edit
    defaults:  { _controller: AppBundle:Category:edit }
    requirements:
                    id: \d+

addcategorie:
    path:      /categories/new
    defaults:  { _controller: AppBundle:Category:new }

deletecategorie:
    path:      /categories/{id}/delete
    defaults:  { _controller: AppBundle:Category:delete }
    requirements:
                    id: \d+
    options:
                expose: true
#--------------------- Roles -------------------#
addrole:
    path:      /roles/new
    defaults:  { _controller: AppBundle:Role:new }
editrole:
    path:      /roles/{id}/edit
    defaults:  { _controller: AppBundle:Role:edit }
    requirements:
                    id: \d+
listroles:
    path:      /roles
    defaults:  { _controller: AppBundle:Role:showAll }

deleterole:
    path:      /roles/{id}/delete
    defaults:  { _controller: AppBundle:Role:delete }
    requirements:
                    id: \d+
    options:
                expose: true
#--------------------- Users -------------------#
listusers:
    path:      /utilisateurs
    defaults:  { _controller: AppBundle:Utilisateur:showAll }

adduser:
    path:      /utilisateurs/new
    defaults:  { _controller: AppBundle:Utilisateur:new }

edituser:
    path:      /utilisateurs/{id}/edit
    defaults:  { _controller: AppBundle:Utilisateur:edit }
    requirements:
                    id: \d+
deleteuser:
    path:      /utilisateurs/{id}/delete
    defaults:  { _controller: AppBundle:Utilisateur:delete }
    requirements:
                    id: \d+
    options:
                expose: true}

#--------------------- Commande clients -------------------#

listbcc:
    path:      /clients/commandes
    defaults:  { _controller: AppBundle:CommandeClient:showAll }

addcommandec:
    path:      /commandes/add
    defaults:  { _controller: AppBundle:Client:addCommande }

editcommandec:
    path:      /clients/commandes/{id}/edit
    defaults:  { _controller: AppBundle:CommandeClient:editCommande }
    requirements:
                id: \d+

#--------------------- Commande clients -------------------#

listbcf:
    path:      /fournisseurs/commandes
    defaults:  { _controller: AppBundle:CommandeFournisseur:showAll }

addcommandef:
    path:      /fournisseurs/commandes/add
    defaults:  { _controller: AppBundle:CommandeFournisseur:addCommande }

editcommandef:
    path:      /fournisseurs/commandes/{id}/edit
    defaults:  { _controller: AppBundle:CommandeFournisseur:editCommande }
    requirements:
                id: \d+


confirmlot:
    path:      /fournisseurs/commandes/{id}/lot/confirm
    defaults:  { _controller: AppBundle:Lot:index }
    requirements:
            id: \d+
#--------------------- Produits -------------------#
listproduits:
    path:      /produits
    defaults:  { _controller: AppBundle:Produit:showAll }

addproduit:
    path:      /produits/new
    defaults:  { _controller: AppBundle:Produit:newProduit }

checkemail:
    path:      /checkemail/{email}
    defaults:  { _controller: AppBundle:Client:CheckEmail }
    requirements:
            email: "([\\w-+]+(?:\\.[\\w-+]+)*@(?:[\\w-]+\\.)+[a-zA-Z]{2,7})"
listfacturesclients:
    path:      /facturesclients
    defaults:  { _controller: AppBundle:FactureClient:showAll }

viewfactureclient:
    path:      /factures/{id}/view
    defaults:  { _controller: AppBundle:FactureClient:view }
    requirements:
            id: \d+
payerfacture:
    path:      /factures/{id}/payer
    defaults:  { _controller: AppBundle:FactureClient:payer }
    requirements:
            id: \d+
impayerfacture:
    path:      /factures/{id}/impayer
    defaults:  { _controller: AppBundle:FactureClient:impayer }
    requirements:
            id: \d+
annulerfacture:
    path:      /factures/{id}/annuler
    defaults:  { _controller: AppBundle:FactureClient:annuler }
    requirements:
            id: \d+

activateuser:
    path:      /activate
    defaults:  { _controller: AppBundle:Reset:activateUser }
promoteuser:
    path:      /promote
    defaults:  { _controller: AppBundle:Reset:promoteUser }


#--------------------- Fournisseurs -------------------#

initconfig:
    path:      /config
    defaults:  { _controller: AppBundle:Configuration:index }



loadingconfig:
    path:      /loading
    defaults:  { _controller: AppBundle:Configuration:loading }

configurationgenerale:
    path:      /configuration/{id}/generale
    defaults:  { _controller: AppBundle:Configuration:edit }
    requirements:
                id: \d+

pagenotallowed:
    path:     /pagenotallowed
    defaults: { _controller: AppBundle:Test:notallowed }




















pageNotFound:
    path:      /{path}
    defaults:  { _controller: AppBundle:Test:notfound, path: '' }
    requirements:
        path: .*















